services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      # Эти переменные будут использоваться контейнером PostgreSQL для инициализации базы данных
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      # Проброс порта с хоста (слева) в контейнер (справа)
      # Это то же самое, что вы указывали: localhost:5432
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      # Важно: сохранение данных базы данных на хосте, чтобы они не потерялись при перезапуске контейнера
      - db_data:/var/lib/postgresql/data

volumes:
  # Определение именованного тома Docker для хранения данных
  db_data:
